export { TitlePage } from "./TitlePage";
export { ApprovalPage } from "./ApprovalPage";
export { AbbreviationPage } from "./AbbreviationPage";
export { ExplanatoryPage } from "./ExplanatoryPage";
export { SyllabusPage } from "./SyllabusPage";
export { CalendarPage } from "./CalendarPage";
export { ThematicPage } from "./ThematicPage";
export { EvaluationPage } from "./EvaluationPage";
export { OrganizationPage } from "./OrganizationPage";